{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "FireAnt RESTFUL API",
    "description": "Tài liệu đặc tả FireAnt RESTFUL API v1.0.0"
  },
  "host": "restv2.fireant.vn",
  "schemes": [
    "https"
  ],
  "paths": {
    "/academy/subjects": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy danh sách chủ đề khóa học",
        "operationId": "Academy_GetCourseSubjects",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/subjects/{subjectId}": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy thông tin chủ đề khóa học",
        "operationId": "Academy_GetCourseSubject",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses/{courseId}": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy thông tin khóa học theo ID",
        "operationId": "Academy_GetCourse",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses/levels": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy danh sách tất cả cấp độ của các khóa học",
        "operationId": "Academy_GetAllCoursesLevel",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy danh sách khóa học",
        "operationId": "Academy_GetCourses",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses/recordCount": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy số lượng khóa học",
        "operationId": "Academy_GetCoursesCount",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses/{courseID}/thumbnail": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy ảnh đại diện của khóa học",
        "operationId": "Academy_GetCourseImage"
      }
    },
    "/academy/courses/{courseId}/lessons": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy danh sách bài giảng của khóa học",
        "operationId": "Academy_GetLessons",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/courses/{courseId}/isEnrolled": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Kiểm tra xem user đã đăng ký khóa học hay chưa",
        "operationId": "Academy_CheckEnrollment",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/lessons/{lessonId}": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy thông tin bài giảng theo ID",
        "operationId": "Academy_GetLesson",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/news": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy danh sách tin tức",
        "operationId": "Academy_GetNews",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/news/{newsId}": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy thông tin của tin tức theo ID",
        "operationId": "Academy_GetNews",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/news/recordCount": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy số lượng tin tức",
        "operationId": "Academy_GetNewsCount",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/news/{newsId}/thumbnail": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy ảnh đại diện của tin",
        "operationId": "Academy_GetNewsThumbnail"
      }
    },
    "/academy/classes/{classId}/teachers": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy danh sách giảng viên của lớp học",
        "operationId": "Academy_GetTeacherAssignments",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy danh sách các lớp học",
        "operationId": "Academy_GetClasses",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes/{classId}/schedule": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy thông tin lịch học",
        "operationId": "Academy_GetCourseSchedules",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes/ownedClasses": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy danh sách lớp học của tôi",
        "operationId": "Academy_GetOwnedClass",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes/ownedClasses/{classId}/meeting": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy thông tin dạy trực tuyến",
        "operationId": "Academy_GenerateOwnedSignature",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes/ownedClasses/{classId}/schedules/{scheduleId}/status": {
      "put": {
        "tags": [
          "Academy"
        ],
        "summary": "Cập nhật trạng thái buổi học",
        "operationId": "Academy_UpdateScheduleStatus",
        "security": [
          {
            "oauth2": [
              "academy-write"
            ]
          }
        ]
      }
    },
    "/academy/classes/enrolledClasses": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy danh sách lớp học đã đăng ký",
        "operationId": "Academy_GetEnrolledClass",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/classes/enrolledClasses/{classId}/meeting": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy thông tin học trực tuyến",
        "operationId": "Academy_GenerateEnrolledSignature",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy": {
      "post": {
        "tags": [
          "Academy"
        ],
        "summary": "Đăng ký khóa học",
        "operationId": "Academy_Enroll",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/enrollments/{enrollmentId}": {
      "get": {
        "tags": [
          "Academy"
        ],
        "summary": "Lấy thông tin đăng ký khóa học",
        "operationId": "Academy_GetEnrollment",
        "security": [
          {
            "oauth2": [
              "academy-read"
            ]
          }
        ]
      }
    },
    "/academy/{enrollmentId}": {
      "put": {
        "tags": [
          "Academy"
        ],
        "summary": "Duyệt đơn hàng đăng ký khóa học",
        "operationId": "Academy_ProcessEnrollment",
        "security": [
          {
            "oauth2": [
              "academy-write"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/bank-account/{accountId}": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Trả về thông tin chuyển khoản tiền.",
        "operationId": "Accounts_BankAccount",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Trả về danh sách tài khoản tại công ty chứng khoán của user.",
        "operationId": "Accounts_Accounts",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/state": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Lấy trạng thái tài khoản tại công ty chứng khoán",
        "operationId": "Accounts_AccountState",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/state": {
      "get": {
        "tags": [
          "Accounts"
        ],
        "summary": "Lấy trạng thái tài khoản tại công ty chứng khoán",
        "operationId": "Accounts_AccountState",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/admin/user-info": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "Lấy thông tin user theo id",
        "operationId": "Admin_GetUserInfo",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/admin/block-user": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Block 1 user",
        "operationId": "Admin_BlockUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/admin/yesterday-new-users": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "Danh sách user mới đăng ký hôm trước",
        "operationId": "Admin_GetYesterdayNewUsers",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/admin/news": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Tạo tin tức",
        "operationId": "Admin_InsertNews",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/admin/news/{postId}": {
      "put": {
        "tags": [
          "Admin"
        ],
        "summary": "Sửa tin tức",
        "operationId": "Admin_UpdateNews",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Admin"
        ],
        "summary": "Xóa tin tức",
        "operationId": "Admin_DeleteNews",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/admin/upload-banner": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Upload ảnh banner quảng cáo vào NAS server",
        "operationId": "Admin_UploadBanner",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/admin/upload-ads-json": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Upload file ads.json vào NAS server",
        "operationId": "Admin_UploadAdsJson",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/admin/upload-ads-content": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Upload file JSON hoặc ảnh cho page content vào NAS server.",
        "operationId": "Admin_UploadAdsContentJson",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/admin/upload-file": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Upload file vào NAS server theo thư mục tùy chỉnh",
        "operationId": "Admin_UploadFile",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/admin/upload-image": {
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Upload ảnh vào NAS server",
        "operationId": "Admin_UploadImage",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/authentication/anonymous-login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Đăng nhập nặc danh",
        "operationId": "Authentication_AnonymousLogin"
      }
    },
    "/authentication/login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Đăng nhập bằng mật khấu",
        "operationId": "Authentication_Login"
      }
    },
    "/authentication/apple-login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Đăng nhập Apple",
        "operationId": "Authentication_AppleLogin"
      }
    },
    "/authentication/google-login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Đăng nhập Google",
        "operationId": "Authentication_GoogleLogin"
      }
    },
    "/authentication/facebook-login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Đăng nhập Facebook",
        "operationId": "Authentication_FacebookLogin"
      }
    },
    "/authentication/registration": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Đăng ký tài khoản",
        "operationId": "Authentication_Register"
      }
    },
    "/authentication/password-reset": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Đặt lại mật khẩu",
        "operationId": "Authentication_ForgotPassword"
      }
    },
    "/authentication/email-confirmation": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Gửi email xác nhận tài khoản",
        "operationId": "Authentication_SendConfirmEmail"
      }
    },
    "/authentication/refresh-token": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Refresh token",
        "operationId": "Authentication_RefreshToken"
      }
    },
    "/bonds/categories": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Lấy danh sách các danh mục trái phiếu",
        "operationId": "Bond_GetCategories",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/filter": {
      "post": {
        "tags": [
          "Bond"
        ],
        "summary": "Lọc và tìm kiếm trái phiếu",
        "operationId": "Bond_FilterBonds"
      }
    },
    "/bonds/issuer/{symbol}": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Lấy danh sách trái phiếu theo mã tổ chức phát hành",
        "operationId": "Bond_GetBondsBySymbol",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/{bondCode}": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Lấy thông tin chi tiết một mã trái phiếu",
        "operationId": "Bond_GetBondDetail",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/{bondCode}/cashflow": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Lấy lịch dòng tiền tương lai của trái phiếu",
        "operationId": "Bond_GetBondFutureCashFlow",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/stats/issuers/top-debt": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Top doanh nghiệp có dư nợ trái phiếu lớn nhất",
        "operationId": "Bond_GetTopIssuersByDebt",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/stats/bonds/high-yield": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Danh sách trái phiếu có lãi suất cao nhất",
        "operationId": "Bond_GetHighYieldBonds",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/stats/bonds/maturing-soon": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Danh sách trái phiếu sắp đáo hạn",
        "operationId": "Bond_GetBondsMaturingSoon",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/bonds/stats/industries": {
      "get": {
        "tags": [
          "Bond"
        ],
        "summary": "Thống kê quy mô phát hành theo ngành nghề (ICB)",
        "operationId": "Bond_GetIndustryStatistics",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/brokers": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Trả về danh sách công ty chứng khoán",
        "operationId": "Brokers_Brokers"
      }
    },
    "/brokers/{brokerId}/link-user-url": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Lấy liên kết dùng để kết nối tài khoản tại công ty chứng khoán với tài khoản FireAnt.",
        "operationId": "Brokers_LinkUserUrl",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/open-account-url": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Lấy liên kết dùng để mở tài khoản tại công ty chứng khoán.",
        "operationId": "Brokers_OpenAccountUrl",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/users/{identityNumber}": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Lấy tên tài khoản tại công ty chứng khoán theo số chứng minh thư",
        "operationId": "Brokers_GetBrokerUserName",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/job-names": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Lấy danh sách công việc.",
        "operationId": "Brokers_GetJobNames",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/job-positions": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Lấy danh sách vị trí công việc.",
        "operationId": "Brokers_GetJobPositions",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/referrer-info": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Lấy thông tin người giới thiệu tại công ty chứng khoán.",
        "operationId": "Brokers_GetReferrerInfo",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/banks": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Lấy danh sách ngân hàng.",
        "operationId": "Brokers_GetBanks",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/cif-branches/{branch}": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Lấy danh sách ngân hàng.",
        "operationId": "Brokers_GetCIFBranches",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/kyc-required": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Cần KYC trước để có thể giao dịch",
        "operationId": "Brokers_KycRequired",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/welcome-link": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Lấy welcome link.",
        "operationId": "Brokers_GetWelcomeLink",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/common-banners": {
      "get": {
        "tags": [
          "Brokers"
        ],
        "summary": "Lấy common banners.",
        "operationId": "Brokers_GetBanners",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/brokers/{brokerId}/webhook": {
      "post": {
        "tags": [
          "Brokers"
        ],
        "summary": "Webhook nhận trạng thái từ CTCK.",
        "operationId": "Brokers_BrokerWebhook"
      }
    },
    "/broker-users": {
      "get": {
        "tags": [
          "BrokerUsers"
        ],
        "summary": "Trả về danh sách user chứng khoán đã kết nối với tài khoản FireAnt",
        "operationId": "BrokerUsers_BrokerUsers",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}": {
      "delete": {
        "tags": [
          "BrokerUsers"
        ],
        "summary": "Xóa user chứng khoán đã kết nối với tài khoản FireAnt",
        "operationId": "BrokerUsers_DeleteBrokerUser",
        "security": [
          {
            "oauth2": [
              "accounts-write"
            ]
          }
        ]
      }
    },
    "/chat/notify": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "Gửi thông báo",
        "operationId": "Chat_Notify"
      }
    },
    "/chat/images": {
      "post": {
        "tags": [
          "Chat"
        ],
        "summary": "Upload ảnh cho tin nhắn",
        "operationId": "Chat_UpdateImage",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/chat/images/{key}": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "Lấy ảnh trong thông điệp",
        "operationId": "Chat_GetChatImage"
      }
    },
    "/events/search": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Tìm kiếm sự kiện",
        "operationId": "Events_Search",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/executions": {
      "get": {
        "tags": [
          "Executions"
        ],
        "summary": "Trả về danh sách lệnh khớp trong phiên của 1 mã chứng khoán",
        "operationId": "Executions_Executions",
        "security": [
          {
            "oauth2": [
              "orders-read"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/is-register": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Check if an account is already registered",
        "operationId": "Fmarket_CheckAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/register-account": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create new Fmarket account",
        "operationId": "Fmarket_RegisterAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/get-account-info": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve Fmarket’s account detail",
        "operationId": "Fmarket_GetAccountInfo",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/link-account/create": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create linked fmarket account",
        "operationId": "Fmarket_CreateLinkAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/link-account/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm linked fmarket account",
        "operationId": "Fmarket_ConfirmLinkAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/get-access-code": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get accessCode to login to web",
        "operationId": "Fmarket_GetAccessCode",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/trading-contract-list": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve Investor’s trading contract list",
        "operationId": "Fmarket_GetTradingContractList",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/esign/create": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Only user have isAllowSign=true in trading contract response can sign",
        "operationId": "Fmarket_CreateSignFmarketContract",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/accounts/esign/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm sign",
        "operationId": "Fmarket_ConfirmESign",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/estimate-purchase": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Calculate estimation of volume/fee for purchase order",
        "operationId": "Fmarket_EstimatePurchaseOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-purchase-order/request": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create purchase order",
        "operationId": "Fmarket_CreatePurchaseOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/v2/orders/create-purchase-order/request": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create purchase order",
        "operationId": "Fmarket_CreatePurchaseOrderV2",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-purchase-order/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm purchase order",
        "operationId": "Fmarket_ConfirmPurchaseOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/v2/orders/create-purchase-order/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm purchase order",
        "operationId": "Fmarket_ConfirmPurchaseOrderV2",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/estimate-sale": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Calculate estimation of amount/fee for sale order",
        "operationId": "Fmarket_EstimateSaleOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-sale-order/request": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create sale order",
        "operationId": "Fmarket_CreateSaleOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-sale-order/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm sale order",
        "operationId": "Fmarket_ConfirmSaleOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/get-destination-products": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get list of destination product for convert",
        "operationId": "Fmarket_GetListOfDestinationProduct",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/estimate-convert": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Calculate estimation of amount/fee/tax for convert order",
        "operationId": "Fmarket_EstimateConvertOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-convert-order/request": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Create convert order",
        "operationId": "Fmarket_CreateConvertOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/create-convert-order/confirm": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Confirm convert order",
        "operationId": "Fmarket_ConfirmConvertOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/cancel-order": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Cancel order (if supported, please check field: allowed_cancel=true)",
        "operationId": "Fmarket_CancelOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/get-order-detail": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve order detail",
        "operationId": "Fmarket_GetOrderDetail",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/filter-orders": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Query list of orders",
        "operationId": "Fmarket_FilterOrders",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/orders/filter-transactions": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve transaction list",
        "operationId": "Fmarket_FilterTransactions",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/assets/filter-asset-funds": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve asset funds",
        "operationId": "Fmarket_FilterAssetFunds",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/assets/filter-assets": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve assets",
        "operationId": "Fmarket_FilterAssets",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/markets/get-product-detail": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Retrieve Fmarket’s product detail",
        "operationId": "Fmarket_GetProductDetail",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/markets/filter-products": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Query list of products",
        "operationId": "Fmarket_FilterProducts",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/markets/issuer-list": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get list issuers",
        "operationId": "Fmarket_GetIssuers",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/static/provinces": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get province list",
        "operationId": "Fmarket_GetProvinces",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/static/nationalities": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get nationality  list",
        "operationId": "Fmarket_GetNationalities",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/static/place-of-issue-id-list": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get place of issue id list",
        "operationId": "Fmarket_GetPlaceOfIssueIDList",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/static/banks": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get bank list",
        "operationId": "Fmarket_GetBanks",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/fmarket/static/get-nav-history": {
      "post": {
        "tags": [
          "Fmarket"
        ],
        "summary": "Get Product NAV History",
        "operationId": "Fmarket_GetProductNavHistory",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/hashtags/search": {
      "get": {
        "tags": [
          "HashTags"
        ],
        "summary": "Tìm kiếm chủ đề (hashtag)",
        "operationId": "HashTags_Search",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/hashtags/{hashTagId}/posts": {
      "get": {
        "tags": [
          "HashTags"
        ],
        "summary": "Lấy danh sách bài viết liên quan tới 1 chủ đề",
        "operationId": "HashTags_GetHashTagPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/icb/{industryCode}/symbols": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "Lấy danh sách mã chứng khoán trong ngành",
        "operationId": "ICB_GetSymbolsInIndustry",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/{industryCode}/statistics": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "Lấy thống kê dữ liệu thời điểm hiện tại của ngành",
        "operationId": "ICB_GetCurrentIndustryStats",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/statistics": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "Lấy thống kê dữ liệu thời điểm hiện tại của tất cả ngành",
        "operationId": "ICB_GetAllLatestIndustryStatistics",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/{industryCode}/financial-data": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "Lấy dữ liệu tài chính  của ngành",
        "operationId": "ICB_GetFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/financial-data": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "Lấy dữ liệu tài chính mới nhất của tất cả ngành",
        "operationId": "ICB_GetAllLatestIndustryFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/{industryCode}/historical-index": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "Lấy dữ liệu chỉ số  của ngành",
        "operationId": "ICB_GetHistoricalIndustryIndex",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/latest-index": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "Lấy dữ liệu tài chính mới nhất của tất cả ngành",
        "operationId": "ICB_GetAllLatestIndustryIndex",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "Lấy danh sách ngành",
        "operationId": "ICB_GetIndustries",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/industry-info": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "Lấy thông tin ngành theo danh sách mã chứng khoán",
        "operationId": "ICB_GetIndustryInfo",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/icb/{industryCode}/rrg": {
      "get": {
        "tags": [
          "ICB"
        ],
        "summary": "Lấy thống kê RRG",
        "operationId": "ICB_GetRRG",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/individuals/search": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Tìm kiếm cá nhân",
        "operationId": "Individuals_Search",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/photo": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Lấy ảnh một cá nhân",
        "operationId": "Individuals_GetIndividualPhoto"
      }
    },
    "/individuals/{individualId}/posts": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Lấy danh sách bài viết liên quan tới một cá nhân",
        "operationId": "Individuals_GetIndividualPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/profile": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Lấy hồ sơ một cá nhân",
        "operationId": "Individuals_GetIndividualProfile",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/jobs": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Lấy danh sách công việc của một cá nhân",
        "operationId": "Individuals_GetIndividualJobs",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/assets": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Lấy danh sách tài sản của một cá nhân",
        "operationId": "Individuals_GetIndividualAssets",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/relations": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Lấy danh sách mối quan hệ trong gia đình của một cá nhân",
        "operationId": "Individuals_GetIndividualRelations",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/{individualId}/transactions": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Lấy danh sách giao dịch mua/bán chứng khoán của một cá nhân",
        "operationId": "Individuals_GetIndividualTransactions",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/richest": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Lấy danh sách người giàu trên sàn chứng khoán",
        "operationId": "Individuals_GetRichestIndividuals",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/gainers": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Lấy danh sách TOP cá nhân tăng tài sản trong ngày trên sàn chứng khoán",
        "operationId": "Individuals_GetTopWinnerRichestIndividuals",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/individuals/losers": {
      "get": {
        "tags": [
          "Individuals"
        ],
        "summary": "Lấy danh sách TOP cá nhân giảm tài sản trong ngày trên sàn chứng khoán",
        "operationId": "Individuals_GetTopLoserRichestIndividuals",
        "security": [
          {
            "oauth2": [
              "individuals-read"
            ]
          }
        ]
      }
    },
    "/industries/{industryCode}/historical-stats": {
      "get": {
        "tags": [
          "Industries"
        ],
        "summary": "Lấy thống kê dữ liệu quá khứ của ngành",
        "operationId": "Industries_GetHistoricalIndustryStats",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/industries/{industryCode}/current-stats": {
      "get": {
        "tags": [
          "Industries"
        ],
        "summary": "Lấy thống kê dữ liệu thời điểm hiện tại của ngành",
        "operationId": "Industries_GetCurrentIndustryStats",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/industries/current-stats": {
      "get": {
        "tags": [
          "Industries"
        ],
        "summary": "Lấy thống kê dữ liệu thời điểm hiện tại của tất cả ngành",
        "operationId": "Industries_GetAllCurrentIndustryStats",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/industries": {
      "get": {
        "tags": [
          "Industries"
        ],
        "summary": "Lấy danh sách ngành",
        "operationId": "Industries_GetIndustries",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/industries/{industryCode}/rrg": {
      "get": {
        "tags": [
          "Industries"
        ],
        "summary": "Lấy thống kê RRG",
        "operationId": "Industries_GetRRG",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/instruments": {
      "get": {
        "tags": [
          "Instruments"
        ],
        "summary": "Trả danh sách toàn bộ mã chứng khoán",
        "operationId": "Instruments_AllInstruments"
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/instruments": {
      "get": {
        "tags": [
          "Instruments"
        ],
        "summary": "Trả danh sách mã chứng khoán tài khoản được phép giao dịch",
        "operationId": "Instruments_Instruments",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "Lấy danh sách thuật ngữ",
        "operationId": "Investopedia_GetTerms",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/recordCount": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "Lấy số lượng thuật ngữ",
        "operationId": "Investopedia_GetTermsCount",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/search": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "Tìm kiếm thuật ngữ theo từ khóa",
        "operationId": "Investopedia_SearchTerms",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/keywords/recordCount": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "Lấy số lượng thuật ngữ theo từ khóa",
        "operationId": "Investopedia_GetTermsByKeywordsCount",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/{termKey}": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "Lấy thông tin thuật ngữ theo tên",
        "operationId": "Investopedia_GetTermByName",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/{termId}": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "Lấy thông tin thuật ngữ theo ID",
        "operationId": "Investopedia_GetTermById",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/categories": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "Lấy danh sách danh mục thuật ngữ",
        "operationId": "Investopedia_GetInvestopediaCategories",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/investopedia/terms/categories/{categoryId}": {
      "get": {
        "tags": [
          "Investopedia"
        ],
        "summary": "Lấy thông tin danh mục thuật ngữ",
        "operationId": "Investopedia_GetInvestopediaCategory",
        "security": [
          {
            "oauth2": [
              "investopedia-read"
            ]
          }
        ]
      }
    },
    "/ir/contracts": {
      "get": {
        "tags": [
          "IR"
        ],
        "summary": "Lấy tất cả hợp đồng IR",
        "operationId": "IR_GetAllContracts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/ir/contracts/{symbol}": {
      "get": {
        "tags": [
          "IR"
        ],
        "summary": "Lấy chi tiết hợp đồng IR của 1 mã chứng khoán",
        "operationId": "IR_GetLastContractBySymbol",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/ir/latest-statistics/{symbol}": {
      "get": {
        "tags": [
          "IR"
        ],
        "summary": "Lấy thống kê hoạt động IR của 1 mã chứng khoán",
        "operationId": "IR_GetLatestIRContractStatistics",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/ir/historical-statistics/{symbol}": {
      "get": {
        "tags": [
          "IR"
        ],
        "summary": "Lấy lịch sử hoạt động IR của 1 mã chứng khoán",
        "operationId": "IR_GetHistoricalIRContractStatistics",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/ir/post-statistics/{symbol}": {
      "get": {
        "tags": [
          "IR"
        ],
        "summary": "Lấy thống kê hoạt động IR của các bài viết của 1 mã chứng khoán",
        "operationId": "IR_GetIRPostStatisticsBySymbol",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/macro-data/types": {
      "get": {
        "tags": [
          "Macro"
        ],
        "summary": "Lấy danh sách các loại dữ liệu vĩ mô",
        "operationId": "Macro_GetMacroIndicatorTypes",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/macro-data/{type}/info": {
      "get": {
        "tags": [
          "Macro"
        ],
        "summary": "Lấy dữ liệu vĩ mô theo loại",
        "operationId": "Macro_GetMacroIndicatorInfo",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/me/push-tokens": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Đăng ký token để push",
        "operationId": "Me_RegisterPushToken",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/recent-symbols": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy các mã chứng khoán gần đây mà user đã xem",
        "operationId": "Me_GetRecentSymbols",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Cập nhật các mã chứng khoán gần đây mà user đã xem",
        "operationId": "Me_UpdateRecentSymbols",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/web-pushs": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Gửi web push",
        "operationId": "Me_SendPush",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/web-pushs-topic": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Gửi web push tới topic",
        "operationId": "Me_SendPushToTopic",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/push-topic-subscribers": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Đăng ký push topic",
        "operationId": "Me_SubscribeToTopic",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/push-topic-unsubscribers": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Bỏ đăng ký push topic",
        "operationId": "Me_UnsubscribeToTopic",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/emails": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Gửi email",
        "operationId": "Me_SendEmail",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/fbtoken": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy token để xác thực, dùng các dịch vụ lưu trữ trên Firebase",
        "operationId": "Me_GetFirebaseToken",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/phone-number": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy số điện thoại của user",
        "operationId": "Me_GetPhoneNumber",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Cập nhật số điện thoại của user",
        "operationId": "Me_UpdateUserPhoneNumber",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/phone-number/verify": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Xác thực số điện thoại của user",
        "operationId": "Me_VerifyUserPhoneNumber",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/profile": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy hồ sơ của 1 user",
        "operationId": "Me_GetUserProfile",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Cập nhật hồ sơ của 1 user",
        "operationId": "Me_UpdateUserProfile",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/settings": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy các thiết lập hiện tại của user",
        "operationId": "Me_GetUserSettings",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Cập nhật các thiết lập của user",
        "operationId": "Me_UpdateUserSettings",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/purchased-items": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy thông tin các sản phẩm người dùng đã mua",
        "operationId": "Me_GetPurchasedItems",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/account": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy thông tin tổng hợp tài khoản của user",
        "operationId": "Me_GetUserAccount",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/password": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Kiểm tra tài khoản đã đặt mật khẩu chưa",
        "operationId": "Me_HasPassword",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Thay đổi mật khẩu",
        "operationId": "Me_ChangePassword",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Đặt mật khẩu",
        "operationId": "Me_SetPassword",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/avatar": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Thay đổi avatar",
        "operationId": "Me_UpdateAvatar",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/authentic": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Đăng ký chính chủ",
        "operationId": "Me_UpdateUserAuthentic",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/extra-info": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Cập nhật thông tin bổ sung cho user",
        "operationId": "Me_UpdateUserExtraInfo",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/posts/stream": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách bài viết được hiển thị cho user",
        "operationId": "Me_GetStreamPosts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/posts": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách bài viết của user",
        "operationId": "Me_GetPosts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/blocked-users": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách người dùng bạn đang block",
        "operationId": "Me_GetBlockedUsers",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Block 1 user",
        "operationId": "Me_BlockUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/blocked-users/{blockedUserId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Unblock 1 user",
        "operationId": "Me_UnblockUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/followers": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách người đang theo dõi bạn",
        "operationId": "Me_GetFollowers",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/following": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách người dùng mà bạn đang theo dõi",
        "operationId": "Me_GetFollowing",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Theo dõi 1 user",
        "operationId": "Me_FollowUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/following/{followedUserId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Bỏ theo dõi 1 user",
        "operationId": "Me_UnfollowUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/hashtags": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách hashtag đang theo dõi",
        "operationId": "Me_GetUserHashTags",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Theo dõi 1 hashtag",
        "operationId": "Me_FollowHashTag",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/hashtags/{hashTagId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Bỏ theo dõi 1 hashtag",
        "operationId": "Me_UnfollowHashTag",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/notifications/new": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy số lượng thông báo mới",
        "operationId": "Me_GetNewNotificationCount",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Reset lại số lượng thông báo mới",
        "operationId": "Me_ResetNewNotificationCount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/notifications": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách thông báo",
        "operationId": "Me_GetNotifications",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa hết thông báo",
        "operationId": "Me_ClearNotifications",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/notifications/unread/{notificationId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Đánh dấu 1 thông báo là đã đọc",
        "operationId": "Me_MarkNotificationAsRead",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/notifications/unread": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Đánh dấu tất cả thông báo là đã đọc",
        "operationId": "Me_MarkAllNotificationsAsRead",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/watchlists/{watchlistID}/posts": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy bài viết của watchlist",
        "operationId": "Me_GetWatchlistPosts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/watchlists": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách watchlist",
        "operationId": "Me_GetWatchlists",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Tạo watchlist",
        "operationId": "Me_CreateWatchlist",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/watchlists/{watchlistId}": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy watchlist",
        "operationId": "Me_GetWatchlist",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Cập nhật watchlist",
        "operationId": "Me_UpdateWatchlist",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa watchlist",
        "operationId": "Me_DeleteWatchlist",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/watchlists/orders": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Cập nhật thứ tự hiển thị watchlist",
        "operationId": "Me_UpdateWatchlistOrders",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/chart-templates": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách mẫu biểu đồ",
        "operationId": "Me_GetChartTemplates",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Tạo mẫu biểu đồ",
        "operationId": "Me_CreateChartTemplate",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/following-chart-templates": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách mẫu biểu đồ được chia sẻ",
        "operationId": "Me_GetFollowingChartTemplates",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/fireant-chart-templates": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách mẫu biểu đồ của FireAnt",
        "operationId": "Me_GetFireAntChartTemplates",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/chart-templates/{templateID}": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy nội dung mẫu biểu đồ",
        "operationId": "Me_GetChartTemplateContent",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Lưu mẫu biểu đồ",
        "operationId": "Me_SaveChartTemplate",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa mẫu biểu đồ",
        "operationId": "Me_DeleteChartTemplate",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Me"
        ],
        "summary": "Thay đổi thông tin mẫu biểu đồ",
        "operationId": "Me_UpdateChartTemplate",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/membership": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy thông tin hội viên đã đăng ký",
        "operationId": "Me_GetUserMembership",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/alerts/notifications": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách thông báo",
        "operationId": "Me_GetAlertNotifications",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Cập nhật thông báo",
        "operationId": "Me_UpdateAlertNotifications",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/alerts": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách cảnh báo",
        "operationId": "Me_GetAlertRegistrations",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Thêm đăng ký nhận cảnh báo",
        "operationId": "Me_AddAlertRegistration",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/alerts/{id}": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Cập nhật đăng ký cảnh báo",
        "operationId": "Me_UpdateAlertRegistration",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa đăng ký nhận cảnh báo",
        "operationId": "Me_DeleteAlertRegistration",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/mobile-alerts": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách cảnh báo điện thoại",
        "operationId": "Me_GetMobileAlerts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Thêm đăng ký nhận cảnh báo điện thoại",
        "operationId": "Me_CreateMobileAlert",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/mobile-alerts/{symbol}": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy cảnh báo điện thoại với 1 mã chứng khoán",
        "operationId": "Me_GetMobileAlert",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa đăng ký nhận cảnh báo điện thoại",
        "operationId": "Me_DeleteMobileAlert",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/fireant-screeners": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách bộ lọc mẫu của FireAnt",
        "operationId": "Me_GetFireAntScreeners",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/screeners": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách bộ lọc",
        "operationId": "Me_GetScreeners",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Thêm bộ lọc mới",
        "operationId": "Me_AddScreener",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/screeners/filter": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Thực hiện lọc dựa trên điều kiện json",
        "operationId": "Me_Filter",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/screeners/{id}": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Cập nhật bộ lọc",
        "operationId": "Me_UpdateScreener",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa bộ lọc",
        "operationId": "Me_DeleteScreener",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/workspaces": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách workspace",
        "operationId": "Me_GetWorkspaces",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Thêm workspace mới",
        "operationId": "Me_AddWorkspace",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/workspaces/{id}": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy trạng thái workspace",
        "operationId": "Me_GetWorkspaceState",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Cập nhật bộ lọc",
        "operationId": "Me_UpdateWorkspace",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa workspace",
        "operationId": "Me_DeleteWorkspace",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/room-invitations/{invitationId}": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Ra quyết định với lời mời tham gia nhóm",
        "operationId": "Me_UpdateInvitation",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa lời mời tham gia nhóm",
        "operationId": "Me_DeleteInvitation",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/me/permissions/create-room": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Kiểm tra quyền tạo nhóm của người dùng",
        "operationId": "Me_GetCreateRoomPermission",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/rooms": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách nhóm đang tham gia",
        "operationId": "Me_GetRooms",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/rooms/{roomId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Rởi khỏi nhóm",
        "operationId": "Me_LeaveRoom",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/rooms/{roomId}/nonmember-users": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Danh sách gợi ý người chưa phải thành viên nhóm",
        "operationId": "Me_GetNonMemberUsers",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/verify-identity": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Xác thực danh tính (KYC)",
        "operationId": "Me_VerifyIdentity",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/link": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Link tài khoản đã có tại công ty chứng khoán.",
        "operationId": "Me_LinkBrokerUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/suggest-account-number": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Gợi ý số tài khoản tại công ty chứng khoán.",
        "operationId": "Me_SuggestAccountNumber",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/check-suggest-number": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Kiểm tra số tài khoản có thể chọn tại công ty chứng khoán.",
        "operationId": "Me_CheckSuggestNumber",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/econtract": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy thông tin hợp đồng điện tử mở tài khoản tại CTCK.",
        "operationId": "Me_GetEContractInformation",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/send-otp": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Gửi mã OTP xác thực email.",
        "operationId": "Me_SendOtpEmail",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}/verify-otp": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Xác thực email bằng OTP.",
        "operationId": "Me_VerifyOtp",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/broker-user/{brokerId}": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy trạng thái tài khoản tại công ty chứng khoán.",
        "operationId": "Me_GetBrokerUserStatus",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Tạo tài khoản tại công ty chứng khoán.",
        "operationId": "Me_CreateBrokerUser",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/money-account": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy thông tin tài khoản tiền của người dùng",
        "operationId": "Me_GetAccount",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/money-transactions": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách giao dịch tiền",
        "operationId": "Me_GetTransactions",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Tạo giao dịch tiền",
        "operationId": "Me_CreateTransaction",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/banks": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách ngân hàng được hỗ trợ",
        "operationId": "Me_GetBanks",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/bank-accounts": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách tài khoản ngân hàng",
        "operationId": "Me_GetBankAccounts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Thêm tài khoản ngân hàng",
        "operationId": "Me_AddBankAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/bank-accounts/lookup-name": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Tra cứu tên tài khoản ngân hàng",
        "operationId": "Me_LookupBankAccountName",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/bank-accounts/{bankAccountId}": {
      "delete": {
        "tags": [
          "Me"
        ],
        "summary": "Xóa tài khoản ngân hàng",
        "operationId": "Me_RemoveBankAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/mxv/account": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy thông tin tài khoản hàng hóa MXV",
        "operationId": "Me_GetMXVAccount",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/mxv/orders": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách lệnh giao dịch hàng hóa MXV",
        "operationId": "Me_GetMXVOrders",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/mxv/positions": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy danh sách vị thế mở hàng hóa MXV",
        "operationId": "Me_GetMXVAccountPositions",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/me/mxv/account-request": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Lấy yêu cầu tạo tài khoản giao dịch hàng hóa MXV",
        "operationId": "Me_GetMXVAccountRequest",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Yêu cầu tạo tài khoản giao dịch hàng hóa MXV",
        "operationId": "Me_CreateMXVAccountRequest",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/pin-code": {
      "put": {
        "tags": [
          "Me"
        ],
        "summary": "Đổi pin code",
        "operationId": "Me_ChangePinCode",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/request-sms-otp": {
      "get": {
        "tags": [
          "Me"
        ],
        "summary": "Yêu cầu gửi mã OTP qua SMS",
        "operationId": "Me_RequestSmsOTP",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/fmarket-account": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Tạo tài khoản Fmarket",
        "operationId": "Me_CreateFMarketAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/fmarket-account-confirmation": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Xác nhận liên kết tài khoản Fmarket",
        "operationId": "Me_ConfirmLinkFmarketAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/me/upload-file": {
      "post": {
        "tags": [
          "Me"
        ],
        "summary": "Upload file",
        "operationId": "Me_UploadFile",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/monitoring/status": {
      "get": {
        "tags": [
          "Monitoring"
        ],
        "summary": "Kiểm tra trạng thái API",
        "operationId": "Monitoring_Status"
      }
    },
    "/mxv/brokers": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Lấy danh sách Môi giới",
        "operationId": "MXV_GetBrokers",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/collaborators": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Lấy danh sách Cộng tác viên",
        "operationId": "MXV_GetCollaborators",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/account": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Lấy thông tin chi tiết tài khoản MXV",
        "operationId": "MXV_GetAccountDetail",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Tạo tài khoản MXV (Future, Nano, MXV)",
        "operationId": "MXV_CreateMXVAccount",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/account/status": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Lấy trạng thái tài khoản MXV (Future, Nano, MXV)",
        "operationId": "MXV_GetMXVAccountStatus",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/account/margin-status": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Lấy trạng thái ký quỹ hiện tại",
        "operationId": "MXV_GetMarginStatus",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/account/margin-transactions": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Lấy lịch sử nộp rút ký quỹ",
        "operationId": "MXV_GetMarginTransactions",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/account/deposit-request": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Yêu cầu nạp tiền vào tài khoản MXV",
        "operationId": "MXV_DepositRequest",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/account/withdraw-request": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Yêu cầu rút tiền từ tài khoản MXV",
        "operationId": "MXV_WithdrawRequest",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/account/transfer-money-request": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Yêu cầu chuyển tiền giữa các tài khoản Future, Nano, MXV",
        "operationId": "MXV_TransferMoneyRequest",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/account/money-requests": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Lấy lịch sử yêu cầu nạp/rút/chuyển tiền của người dùng",
        "operationId": "MXV_GetMoneyRequests",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/market/commodities": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Quản lý hàng hoá",
        "operationId": "MXV_GetCommodities",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/market/commodities/{commodityCode}": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Chi tiết hàng hoá",
        "operationId": "MXV_GetCommodityDetail",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/market/contracts": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Quản lý hợp đồng",
        "operationId": "MXV_GetContracts",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/market/contracts/{contractCode}": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Chi tiết hợp đồng",
        "operationId": "MXV_GetContractDetail",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/positions": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Danh sách trạng thái mở",
        "operationId": "MXV_GetPositionsOpen",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/positions/settle": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Danh sách tất toán",
        "operationId": "MXV_GetPositionsSettle",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/transactions": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Danh sách giao dịch",
        "operationId": "MXV_GetTrades",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/orders": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Danh sách lệnh",
        "operationId": "MXV_GetOrders",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Đặt lệnh mới",
        "operationId": "MXV_PlaceOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/orders/{clientOrderId}": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Chi tiết lệnh",
        "operationId": "MXV_GetOrderDetail",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "MXV"
        ],
        "summary": "Sửa lệnh",
        "operationId": "MXV_ReplaceOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "MXV"
        ],
        "summary": "Hủy lệnh",
        "operationId": "MXV_CancelOrder",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/traceability/product": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Truy xuất nguồn gốc sản phẩm vật chất",
        "operationId": "MXV_GetProductTraceability",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/register": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Đăng ký giao hàng vật chất (bên bán)",
        "operationId": "MXV_PhysicalDeliveryRegister",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/cancel": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Huỷ đăng ký giao hàng vật chất",
        "operationId": "MXV_PhysicalDeliveryCancel",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-receive/register": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Đăng ký nhận hàng vật chất (bên mua)",
        "operationId": "MXV_PhysicalReceiveRegister",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-receive/cancel": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Huỷ đăng ký nhận hàng vật chất",
        "operationId": "MXV_PhysicalReceiveCancel",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/deposit": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Đăng ký lưu ký hàng vật chất vào kho (bên bán)",
        "operationId": "MXV_PhysicalDeliveryDeposit",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/cancel-deposit": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Huỷ đăng ký lưu ký hàng vật chất",
        "operationId": "MXV_PhysicalCancelDeposit",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/designated": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Xác nhận giao hàng vật chất chỉ định (bên bán)",
        "operationId": "MXV_PhysicalDeliveryDesignated",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-receive/designated": {
      "post": {
        "tags": [
          "MXV"
        ],
        "summary": "Xác nhận nhận hàng vật chất chỉ định (bên mua)",
        "operationId": "MXV_PhysicalReceiveDesignated",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/history": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Lấy danh sách đăng ký giao/nhận hàng vật chất",
        "operationId": "MXV_GetPhysicalDeliveryHistory",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/history/detail": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Lấy thông tin chi tiết đăng ký giao/nhận hàng vật chất",
        "operationId": "MXV_GetPhysicalDeliveryDetail",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/registrations": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Truy vấn trạng thái đăng ký giao/nhận hàng vật chất",
        "operationId": "MXV_GetPhysicalRegistrations",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/deposit-registrations": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Truy vấn trạng thái đăng ký lưu ký vật chất",
        "operationId": "MXV_GetDepositRegistrations",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/mxv/physical-delivery/transactions": {
      "get": {
        "tags": [
          "MXV"
        ],
        "summary": "Truy vấn trạng thái nhận hàng vật chất tại kho",
        "operationId": "MXV_GetPhysicalTransactions",
        "security": [
          {
            "oauth2": [
              "user-data-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/orders": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "Trả về danh sách lệnh đặt trong phiên",
        "operationId": "Orders_Orders",
        "security": [
          {
            "oauth2": [
              "orders-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Đặt lệnh",
        "operationId": "Orders_CreateOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/orders/otp": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Yêu cầu gửi OTP đặt lệnh",
        "operationId": "Orders_SendOtp",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/orders/{orderId}": {
      "put": {
        "tags": [
          "Orders"
        ],
        "summary": "Sửa lệnh",
        "operationId": "Orders_EditOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Orders"
        ],
        "summary": "Hủy lệnh",
        "operationId": "Orders_DeleteOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/orderHistory": {
      "get": {
        "tags": [
          "OrdersHistory"
        ],
        "summary": "Trả về lịch sử đặt lệnh của tài khoản",
        "operationId": "OrdersHistory_OrderHistory",
        "security": [
          {
            "oauth2": [
              "orders-read"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/orders": {
      "get": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "Trả về danh sách lệnh đặt trong phiên",
        "operationId": "OrdersV2_Orders",
        "security": [
          {
            "oauth2": [
              "orders-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "Đặt lệnh",
        "operationId": "OrdersV2_CreateOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/orders/otp-required": {
      "get": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "Cần OTP để giao dịch",
        "operationId": "OrdersV2_OtpRequired",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/orders/otp": {
      "post": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "Yêu cầu gửi OTP đặt lệnh",
        "operationId": "OrdersV2_SendOtp",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/orders/{orderId}": {
      "put": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "Sửa lệnh",
        "operationId": "OrdersV2_EditOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "OrdersV2"
        ],
        "summary": "Hủy lệnh",
        "operationId": "OrdersV2_DeleteOrder",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/otp/time": {
      "get": {
        "tags": [
          "Otp"
        ],
        "summary": "Lấy giờ máy chủ OTP",
        "operationId": "Otp_RequestSmsOTP",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/otp/sms-otp": {
      "get": {
        "tags": [
          "Otp"
        ],
        "summary": "Yêu cầu gửi mã OTP qua SMS",
        "operationId": "Otp_RequestSmsOtp",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/otp/smart-otp": {
      "get": {
        "tags": [
          "Otp"
        ],
        "summary": "Lấy thông tin đăng ký Smart Otp",
        "operationId": "Otp_GetSmartOtpInfo",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Otp"
        ],
        "summary": "Đăng ký Smart OTP",
        "operationId": "Otp_RegisterSmartOtp",
        "security": [
          {
            "oauth2": [
              "user-data-write"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/positions": {
      "get": {
        "tags": [
          "Positions"
        ],
        "summary": "Trả về vị thế mở của tài khoản",
        "operationId": "Positions_Positions",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/broker-users/{userId}/accounts/{accountId}/positions/{positionId}": {
      "delete": {
        "tags": [
          "Positions"
        ],
        "summary": "Đóng vị thế",
        "operationId": "Positions_ClosePosition",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/positions": {
      "get": {
        "tags": [
          "PositionsV2"
        ],
        "summary": "Trả về vị thế mở của tài khoản",
        "operationId": "PositionsV2_Positions",
        "security": [
          {
            "oauth2": [
              "accounts-read"
            ]
          }
        ]
      }
    },
    "/v2/broker-users/{userId}/accounts/{accountId}/positions/{positionId}": {
      "delete": {
        "tags": [
          "PositionsV2"
        ],
        "summary": "Đóng vị thế",
        "operationId": "PositionsV2_ClosePosition",
        "security": [
          {
            "oauth2": [
              "orders-write"
            ]
          }
        ]
      }
    },
    "/posts/groups": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách nhóm bài viết",
        "operationId": "Posts_GetPostGroups",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/experts": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách chuyên gia",
        "operationId": "Posts_GetExperts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/sources": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách nguồn tin",
        "operationId": "Posts_GetPostSources",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/feed": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy news feed của người dùng",
        "operationId": "Posts_GetNewsFeed",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách bài viết",
        "operationId": "Posts_GetPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Posts"
        ],
        "summary": "Đăng bài viết",
        "operationId": "Posts_InsertPost",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/popular": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách bài viết phổ biến",
        "operationId": "Posts_GetPopularPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/livestream": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách livestream",
        "operationId": "Posts_GetLivestreamPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/video": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách bài viết video",
        "operationId": "Posts_GetVideoPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/video/top": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách video tiêu điểm",
        "operationId": "Posts_GetTopVideos",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/emagazine": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách bài viết emagazine",
        "operationId": "Posts_GetEmagazinePosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/infographic": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách bài viết infographic",
        "operationId": "Posts_GetInfographicPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/individuals": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách bài viết có đề cập tới các cá nhân",
        "operationId": "Posts_GetIndividualRelatedPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/expert-ideas": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách bài viết nhận định chuyên gia",
        "operationId": "Posts_GetExpertIdeas",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/related-posts": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách bài viết liên quan tới 1 bài viết",
        "operationId": "Posts_GetRelatedPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/replies": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách bình luận của 1 bài viết",
        "operationId": "Posts_GetReplies",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/replies/{replyPostId}/index": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy thứ tự của 1 bình luận trong danh sách bình luận của 1 bài viết",
        "operationId": "Posts_GetReplyPostIndex",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/likes": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách người thích 1 bài viết",
        "operationId": "Posts_GetLikes",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Posts"
        ],
        "summary": "Thích bài viết",
        "operationId": "Posts_LikePost",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Posts"
        ],
        "summary": "Bỏ thích bài viết",
        "operationId": "Posts_UnlikePost",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/{postId}": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy nội dung bài viết",
        "operationId": "Posts_GetPost",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Posts"
        ],
        "summary": "Sửa bài viết",
        "operationId": "Posts_UpdatePost",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Posts"
        ],
        "summary": "Xóa bài viết",
        "operationId": "Posts_DeletePost",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/livestream-permission": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Kiểm tra quyền livestream",
        "operationId": "Posts_HasLivestreamPermission",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/kyc-required": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Kiểm tra người dùng có cần KYC khi đăng bài không",
        "operationId": "Posts_HasPostPermission",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/livestream/start": {
      "put": {
        "tags": [
          "Posts"
        ],
        "summary": "Bắt đầu livestream",
        "operationId": "Posts_StartLivestream",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/{postId}/livestream/stop": {
      "put": {
        "tags": [
          "Posts"
        ],
        "summary": "Kết thúc livestream",
        "operationId": "Posts_StopLivestream",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/images/{imageId}": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy ảnh trong bài viết",
        "operationId": "Posts_GetPostImage"
      }
    },
    "/posts/{postId}/abuse-reports": {
      "post": {
        "tags": [
          "Posts"
        ],
        "summary": "Báo cáo xấu bài viết",
        "operationId": "Posts_ReportAbuse",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/link-detail": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy preview của liên kết",
        "operationId": "Posts_GetLinkPreview",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/detected-symbols": {
      "post": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách mã chứng khoán trong nội dung bài viết của liên kết",
        "operationId": "Posts_GetSymbols",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/posts/popular-symbols/{period}": {
      "get": {
        "tags": [
          "Posts"
        ],
        "summary": "Lấy danh sách mã chứng khoán được chia sẻ nhiều",
        "operationId": "Posts_GetPopularSymbols",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/reports/{reportID}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Thông tin về 1 báo cáo",
        "operationId": "Reports_GetReport",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/reports/search": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Tìm kiếm báo cáo",
        "operationId": "Reports_Search",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/reports/categories": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Danh sách danh mục báo cáo",
        "operationId": "Reports_GetCategories",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/reports/sources": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "Danh sách nguồn báo cáo",
        "operationId": "Reports_GetSources",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "Lấy thông tin về room",
        "operationId": "Rooms_GetRoom",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Rooms"
        ],
        "summary": "Cập nhật thông tin nhóm",
        "operationId": "Rooms_UpdateRoomInfo",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Rooms"
        ],
        "summary": "Xóa nhóm",
        "operationId": "Rooms_DeleteRoom",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/top/popular": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "Lấy danh sách nhóm phổ biến",
        "operationId": "Rooms_GetPopularRooms",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms/top/featured": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "Lấy danh sách nhóm đặc sắc",
        "operationId": "Rooms_GetFeaturedRooms",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms/top/recommended": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "Lấy danh sách nhóm được khuyến nghị",
        "operationId": "Rooms_GetRecommendedRooms",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms": {
      "post": {
        "tags": [
          "Rooms"
        ],
        "summary": "Tạo room",
        "operationId": "Rooms_CreateRoom",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/cover-image": {
      "put": {
        "tags": [
          "Rooms"
        ],
        "summary": "Thay đổi ảnh đại diện nhóm",
        "operationId": "Rooms_UpdateRoomCoverImage",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/invitations": {
      "post": {
        "tags": [
          "Rooms"
        ],
        "summary": "Gửi lời mời",
        "operationId": "Rooms_Invite",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/requests": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "Lấy danh sách các yêu cầu tham giá nhóm đang chờ",
        "operationId": "Rooms_GetPendingRequests",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Rooms"
        ],
        "summary": "Gửi yêu cầu tham gia nhóm",
        "operationId": "Rooms_SendRequest",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/requests/{requestId}": {
      "put": {
        "tags": [
          "Rooms"
        ],
        "summary": "Duyệt yêu cầu tham gia nhóm",
        "operationId": "Rooms_UpdateRequest",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Rooms"
        ],
        "summary": "Xóa yêu cầu tham gia nhóm",
        "operationId": "Rooms_DeleteRequest",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/members/{userId}/role": {
      "put": {
        "tags": [
          "Rooms"
        ],
        "summary": "Gán quyền cho thành viên",
        "operationId": "Rooms_AssignRole",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/members": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "Lấy danh sách thành viên nhóm",
        "operationId": "Rooms_GetMembers",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/members/{userId}": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "Lấy thông tin thành viên trong nhóm",
        "operationId": "Rooms_GetMembers",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Rooms"
        ],
        "summary": "Xóa thành viên khỏi nhóm",
        "operationId": "Rooms_RemoveMember",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/blocked-users": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "Lấy danh sách người dùng bị chặn",
        "operationId": "Rooms_GetBlockedUsers",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Rooms"
        ],
        "summary": "Chặn người dùng",
        "operationId": "Rooms_BlockUser",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/blocked-users/{userId}": {
      "delete": {
        "tags": [
          "Rooms"
        ],
        "summary": "Bỏ chặn người dùng",
        "operationId": "Rooms_UnblockUser",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/posts": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "Lấy danh sách bài viết trong nhóm",
        "operationId": "Rooms_GetPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/sticky-posts": {
      "get": {
        "tags": [
          "Rooms"
        ],
        "summary": "Lấy danh sách bài viết đính trong nhóm",
        "operationId": "Rooms_GetStickyPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/rooms/{roomId}/posts/{postId}/sticky": {
      "put": {
        "tags": [
          "Rooms"
        ],
        "summary": "Cập nhật trạng thái đính cho bài viết trong nhóm",
        "operationId": "Rooms_UpdateSticky",
        "security": [
          {
            "oauth2": [
              "posts-write"
            ]
          }
        ]
      }
    },
    "/search": {
      "get": {
        "tags": [
          "Search"
        ],
        "summary": "Tìm kiếm",
        "operationId": "Search_Search",
        "security": [
          {
            "oauth2": [
              "search"
            ]
          }
        ]
      }
    },
    "/search/exact": {
      "get": {
        "tags": [
          "Search"
        ],
        "summary": "Tìm kiếm chính xác",
        "operationId": "Search_SearchExact",
        "security": [
          {
            "oauth2": [
              "search"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Thông tin mã chứng khoán",
        "operationId": "Symbols_GetSymbol",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/search": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Tìm kiếm mã chứng khoán",
        "operationId": "Symbols_Search",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/movers": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "TOP cổ phiếu biến động",
        "operationId": "Symbols_GetTopMovers",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/proprietary-trading-value": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "TOP cổ phiếu được tự doanh mua/bán",
        "operationId": "Symbols_ProprietaryTradingNetValue",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/contribute-to-index": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "TOP mã chứng khoán đóng góp vào index",
        "operationId": "Symbols_TopContributeToIndex",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/posts": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy danh sách bài viết liên quan tới Mã chứng khoán",
        "operationId": "Symbols_GetSymbolPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/rooms": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy danh sách nhóm liên quan tới Mã chứng khoán",
        "operationId": "Symbols_GetSymbolRooms",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/historical-quotes": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy giá quá khứ của Mã chứng khoán",
        "operationId": "Symbols_GetHistoricalQuotes",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/financial-reports": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy báo cáo tài chính tóm tắt của doanh nghiệp",
        "operationId": "Symbols_GetSummaryFinancialReports",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/full-financial-reports": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy báo cáo tài chính đầy đủ của doanh nghiệp",
        "operationId": "Symbols_GetFinancialReports",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/financial-indicators": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy chỉ tiêu tài chính của doanh nghiệp",
        "operationId": "Symbols_GetFinancialIndicators",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/fundamental": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy thông tin cơ bản, quan trọng của 1 Mã chứng khoán",
        "operationId": "Symbols_GetSymbolFundamental",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/profile": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy hồ sơ công ty",
        "operationId": "Symbols_GetInstitutionProfile",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/subsidiaries": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy danh sách công ty con/liên kết của 1 tổ chức",
        "operationId": "Symbols_GetSubCompanies",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/holders": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy danh sách cổ đông lớn của 1 tổ chức",
        "operationId": "Symbols_GetMajorHolders",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/officers": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy danh sách ban lãnh đạo của 1 tổ chức",
        "operationId": "Symbols_GetOfficers",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/holder-transactions": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy danh sách giao dịch (Mua/Bán) của các cổ đông lớn (với cổ phiếu của tổ chức)",
        "operationId": "Symbols_GetMajorHolderTransactions",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/timescale-marks": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy các mốc sự kiện theo thời gian (Báo cáo tài chính, Cổ tức,...)",
        "operationId": "Symbols_GetTimescaleMarks",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/transactions": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy danh sách giao dịch (Mua/Bán) của tổ chức",
        "operationId": "Symbols_GetTransactions",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/transactions/{transactionID}": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy chi tiết 1 giao dịch",
        "operationId": "Symbols_GetTransaction",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/dividends": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy thống kê cổ tức hàng năm",
        "operationId": "Symbols_GetDividends",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/rrg": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy thống kê RRG",
        "operationId": "Symbols_GetRRG",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/estimated-price": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy thông tin định giá",
        "operationId": "Symbols_GetEstimatedPrice",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/commodity-contract": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy thông tin chi tiết hợp đồng tương lai hàng hóa phái sinh",
        "operationId": "Symbols_GetCommodityContractInfo",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/commodities/{category}": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy danh sách hợp đồng tương lai hàng hóa phái sinh theo danh mục",
        "operationId": "Symbols_GetCommoditiesByCategory",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/warrant-info": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy thông tin chi tiết chứng quyền có đảm bảo",
        "operationId": "Symbols_GetWarrantInfo",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/crypto-info": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy thông tin chi tiết crypto",
        "operationId": "Symbols_GetCryptoInfo",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/financial-data": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy thông tin tài chính đầy đủ của doanh nghiệp",
        "operationId": "Symbols_GetFullFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/all-financial-data": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy thông tin tài chính đầy đủ của tất cả doanh nghiệp",
        "operationId": "Symbols_GetAllFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/financial-data-by-period": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy thông tin tài chính đầy đủ của doanh nghiệp theo kỳ báo cáo",
        "operationId": "Symbols_GetFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/dynamic-financial-data": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy thông tin tài chính động để so sánh giữa các doanh nghiệp",
        "operationId": "Symbols_GetDynamicFinancialData",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/bonds": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy danh sách trái phiếu do công ty phát hành",
        "operationId": "Symbols_GetSymbolBonds",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/bonds/{bondCode}": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy chi tiết một trái phiếu cụ thể do công ty phát hành",
        "operationId": "Symbols_GetSymbolBondDetail",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/symbols/{symbol}/bonds/{bondCode}/cashflow": {
      "get": {
        "tags": [
          "Symbols"
        ],
        "summary": "Lấy lịch dòng tiền tương lai của một trái phiếu cụ thể",
        "operationId": "Symbols_GetSymbolBondCashFlow",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/profile": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Lấy hồ sơ của 1 user",
        "operationId": "Users_GetUserProfile",
        "security": [
          {
            "oauth2": [
              "users-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/avatar": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Lấy ảnh đại diện của 1 user",
        "operationId": "Users_GetUserAvatar"
      }
    },
    "/users/active": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Lấy danh sách người dùng tích cực",
        "operationId": "Users_GetMostActive",
        "security": [
          {
            "oauth2": [
              "users-read"
            ]
          }
        ]
      }
    },
    "/users/most-followed": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Lấy danh sách người dùng được theo dõi nhiều",
        "operationId": "Users_GetMostFollowed",
        "security": [
          {
            "oauth2": [
              "users-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/followers": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Lấy danh sách người đang theo dõi 1 user",
        "operationId": "Users_GetFollowers",
        "security": [
          {
            "oauth2": [
              "users-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/following": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Lấy danh sách người dùng mà 1 user đang theo dõi",
        "operationId": "Users_GetFollowing",
        "security": [
          {
            "oauth2": [
              "users-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/symbols": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Lấy danh sách mã chứng khoán quan tâm của 1 user",
        "operationId": "Users_GetUserSymbols",
        "security": [
          {
            "oauth2": [
              "symbols-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/posts": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Lấy danh sách bài viết của 1 user",
        "operationId": "Users_GetUserPosts",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/videos": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Lấy danh sách videos của 1 user",
        "operationId": "Users_GetUserVideos",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    },
    "/users/{userId}/rooms": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Lấy danh sách nhóm đang tham gia của 1 user",
        "operationId": "Users_GetRooms",
        "security": [
          {
            "oauth2": [
              "posts-read"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "oauth2": {
      "type": "oauth2",
      "description": "OAuth2 Implicit Grant",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.fireant.vn/connect/authorize",
      "scopes": {
        "accounts-read": "Đọc danh sách tài khoản giao dịch chứng khoán",
        "accounts-write": "Liên kết tài khoản chứng khoán",
        "orders-read": "Đọc danh sách lệnh giao dịch chứng khoán",
        "orders-write": "Đặt, sửa, hủy lệnh giao dịch chứng khoán",
        "companies-read": "Đọc thông tin doanh nghiệp",
        "companies-write": "Tạo mới, cập nhật, xóa thông tin doanh nghiệp",
        "individuals-read": "Đọc thông tin cá nhân",
        "individuals-write": "Tạo mới, cập nhật, xóa thông tin cá nhân",
        "finance-read": "Đọc thông tin tài chính",
        "finance-write": "Tạo mới, cập nhật, xóa thông tin tài chính",
        "posts-write": "Đăng bài viết",
        "posts-read": "Lấy nội dung các bài viết của cộng đồng",
        "symbols-read": "Đọc thông tin mã chứng khoán",
        "symbols-write": "Tạo mới, cập nhật, xóa mã chứng khoán",
        "users-read": "Đọc dữ liệu công khai của người dùng",
        "user-data-read": "Đọc tất cả dữ liệu của người dùng hiện tại",
        "user-data-write": "Cập nhật tất cả dữ liệu của người dùng hiện tại",
        "search": "Tìm kiếm",
        "academy-read": "Đọc dữ liệu các khóa học",
        "academy-write": "Đăng ký khóa học",
        "blog-read": "Đọc dữ liệu blog",
        "investopedia-read": "Đọc dữ liệu thuật ngữ",
        "commodities-read": "Đọc dữ liệu hàng hóa phái sinh",
        "all_claims": "All",
        "roles": "Role"
      }
    }
  }
}